spring:
  rabbitmq:
    host: 10.71.22.45
    prot: 5672
    username: yhfin
    password: yhfin
  cloud:
    stream:
      bindings:
        entry:
           destination: entry-channel
           contentType: application/json
        memory:
          destination: memory-channel
          contentType: application/json
        analy:
           destination: analy-channel
           contentType: application/json
        result:
          destination: result-channel
          contentType: application/json


server:
  port: 9010


yhtech:
  web:
    swagger: true
feign:
  hystrix:
    enabled: true