spring:
  rabbitmq:
    host: 192.168.74.226
    prot: 5672
    username: yhfin
    password: yhfin
  cloud:
    stream:
      bindings:
        entry:
           destination: entry-channel
           contentType: application/json
        memory:
          destination: memory-channel
          contentType: application/json
        analy:
           destination: analy-channel
           contentType: application/json
        result:
          destination: result-channel
          contentType: application/json



yhtech:
  web:
    swagger: true
feign:
  hystrix:
    enabled: true