spring:
  rabbitmq:
    host: 192.168.100.100
    prot: 5672
    username: admin
    password: 415ilyILY
  cloud:
    stream:
      bindings:
        entry:
           destination: entry-channel
           contentType: application/json
        memory:
          destination: memory-channel
          contentType: application/json
        analy:
           destination: analy-channel
           contentType: application/json
        calculate:
          destination: calculate-channel
          contentType: application/json
        risk:
          destination: risk-channel
          contentType: application/json
        queryCalculate:
          destination: queryCalculate-channel
          contentType: application/json


server:
  port: 9010


yhtech:
  web:
    swagger: true