CREATE OR REPLACE VIEW V_RISK_FUND_VALID_RISK AS
SELECT TO_CHAR(B.I_FUND) AS FUND_ID,A.I_RISK_ID   FROM RISKSET A,FUNDINFOS B WHERE A.VC_CONTROL_LAY = '0' AND INSTR(A.VC_CONTROL_VALUE,'-1') > 0

UNION

SELECT REGEXP_SUBSTR(VC_CONTROL_VALUE,'[0-9]+',1,RN) FUND_ID,A.I_RISK_ID FROM (
SELECT A.VC_CONTROL_VALUE,B.RN,A.I_RISK_ID FROM
(SELECT A.I_RISK_ID,  A.VC_CONTROL_VALUE,LENGTH(A.VC_CONTROL_VALUE)-LENGTH(REPLACE(A.VC_CONTROL_VALUE,',',''))+1 RN FROM RISKSET A WHERE A.VC_CONTROL_LAY = '0' AND INSTR(A.VC_CONTROL_VALUE,'-1') = 0 ) A,
(SELECT LEVEL RN FROM DUAL CONNECT BY ROWNUM <= (SELECT MAX(LENGTH(A.VC_CONTROL_VALUE)-LENGTH(REPLACE(A.VC_CONTROL_VALUE,',',''))+1) RN FROM RISKSET A  WHERE A.VC_CONTROL_LAY = '0' AND INSTR(A.VC_CONTROL_VALUE,'-1') = 0)) B
WHERE A.RN >= B.RN
) A

UNION
SELECT TO_CHAR(B.I_FUND) AS FUND_ID,A.I_RISK_ID FROM  RISKSET A ,GROUPFUNDS B WHERE A.VC_CONTROL_LAY = '1' AND INSTR(A.VC_CONTROL_VALUE,'-1') > 0

UNION

SELECT TO_CHAR(E.I_FUND) AS FUND_ID ,D.I_RISK_ID FROM (
SELECT REGEXP_SUBSTR(VC_CONTROL_VALUE,'[0-9]+',1,RN) GROUP_ID,A.I_RISK_ID FROM (
SELECT A.VC_CONTROL_VALUE,B.RN,A.I_RISK_ID FROM
(SELECT A.I_RISK_ID,  A.VC_CONTROL_VALUE,LENGTH(A.VC_CONTROL_VALUE)-LENGTH(REPLACE(A.VC_CONTROL_VALUE,',',''))+1 RN FROM RISKSET A WHERE A.VC_CONTROL_LAY = '1' AND INSTR(A.VC_CONTROL_VALUE,'-1') = 0 ) A,
(SELECT LEVEL RN FROM DUAL CONNECT BY ROWNUM <= (SELECT MAX(LENGTH(A.VC_CONTROL_VALUE)-LENGTH(REPLACE(A.VC_CONTROL_VALUE,',',''))+1) RN FROM RISKSET A  WHERE A.VC_CONTROL_LAY = '1' AND INSTR(A.VC_CONTROL_VALUE,'-1') = 0 )) B
WHERE A.RN >= B.RN
) A
) D,GROUPFUNDS E WHERE D.GROUP_ID = E.I_GROUP

MINUS

SELECT REGEXP_SUBSTR(VC_CONTROL_DEBAR,'[0-9]+',1,RN) FUND_ID,A.I_RISK_ID FROM (
SELECT A.VC_CONTROL_DEBAR,B.RN,A.I_RISK_ID FROM
(SELECT A.I_RISK_ID,  A.VC_CONTROL_DEBAR,LENGTH(A.VC_CONTROL_DEBAR)-LENGTH(REPLACE(A.VC_CONTROL_DEBAR,',',''))+1 RN FROM RISKSET A WHERE TRIM(A.VC_CONTROL_DEBAR) IS NOT NULL ) A,
(SELECT LEVEL RN FROM DUAL CONNECT BY ROWNUM <= (SELECT MAX(LENGTH(A.VC_CONTROL_DEBAR)-LENGTH(REPLACE(A.VC_CONTROL_DEBAR,',',''))+1) RN FROM RISKSET A WHERE TRIM(A.VC_CONTROL_DEBAR) IS NOT NULL )) B
WHERE A.RN >= B.RN
) A;
