DECLARE
I_EXISTS      NUMBER;
BEGIN
    SELECT COUNT(1) INTO I_EXISTS FROM USER_TAB_COLS A WHERE A.TABLE_NAME = 'RISK_INDEX' AND A.COLUMN_NAME = 'VC_STOCKBOUND_DYNAMIC_SQL';
    
    IF I_EXISTS = 0 THEN
      
       EXECUTE IMMEDIATE 'ALTER TABLE USER_TAB_COLS ADD (VC_STOCKBOUND_DYNAMIC_SQL ARCHAR2(3000))'; 
    
    END IF;
END;