DECLARE

I_EXISTS NUMBER;
BEGIN

  SELECT COUNT(1) INTO I_EXISTS FROM USER_TAB_COLS A WHERE A.TABLE_NAME = 'RISKSET' AND A.COLUMN_NAME = 'VC_GROUPS_DEBAR';
  IF I_EXISTS = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RISKSET ADD( VC_GROUPS_DEBAR VARCHAR2(4000) DEFAULT '' '')';
    
  END IF;

END;