-----------------------------------------------------------------------------------------------------------------------------------
----1. RISK_STOCK_BOUND表格增加字段I_CONFIG_ID I_PARENT_ID
DECLARE

I_EXISTS   NUMBER;
BEGIN
  --删除 RISK_STOCK_BOUND 字段 I_CONFIG_TYPE
  SELECT COUNT(1) INTO I_EXISTS FROM USER_TAB_COLS A WHERE A.TABLE_NAME = 'RISK_STOCK_BOUND' AND A.COLUMN_NAME = 'I_CONFIG_TYPE';
  IF I_EXISTS > 0 THEN
    EXECUTE  IMMEDIATE 'ALTER TABLE RISK_STOCK_BOUND DROP COLUMN I_CONFIG_TYPE' ;
  END IF;
  
  --增加  RISK_STOCK_BOUND   I_CONFIG_ID
  SELECT COUNT(1) INTO I_EXISTS FROM USER_TAB_COLS A WHERE A.TABLE_NAME = 'RISK_STOCK_BOUND' AND A.COLUMN_NAME = 'I_CONFIG_ID';
  IF I_EXISTS = 0 THEN
    EXECUTE  IMMEDIATE 'ALTER TABLE RISK_STOCK_BOUND ADD  (I_CONFIG_ID NUMBER)' ;
  END IF;
  
   --增加  RISK_STOCK_BOUND   I_PARENT_ID
  SELECT COUNT(1) INTO I_EXISTS FROM USER_TAB_COLS A WHERE A.TABLE_NAME = 'RISK_STOCK_BOUND' AND A.COLUMN_NAME = 'I_PARENT_ID';
  IF I_EXISTS = 0 THEN
    EXECUTE  IMMEDIATE 'ALTER TABLE RISK_STOCK_BOUND ADD  (I_PARENT_ID NUMBER)' ;
  END IF;
  
END;
---------------------------------------------------------------------------------------------------------------------------------