server:
  port: 9002                    #应用运行端口

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9000/eureka/

spring:
  rabbitmq:
    host: 192.168.74.226
    prot: 5672
    username: yhfin
    password: yhfin
  cloud:
    config:
      label: dev
      server:
        git: #配置git仓库地址
          basedir: D:/workplace/yhfin/yhfin-risk-cloud-parent
          uri: http://gitlab.yhfin.club:81/risk/server-group/risk-cloud-core.git
          search-paths: yhfin-risk-remote-config
          username: caohui
          password: 415ilyILY
          force-pull: false


