DECLARE
BEGIN
DELETE FROM RISK_FUND_BOUND_CFG A WHERE A.I_BOUND_ID IN ('0','1');

insert into RISK_FUND_BOUND_CFG (I_BOUND_ID, VC_BOUND_NAME, VC_LOAD_VALUE_SQL, VC_CALCU_SQL, VC_NEED_CALCU_SQL, VC_PROPERTY_KEY_VALUE)
values (1, '基金组', 'GFS2.I_FUND = :I_FUND', 'INNER JOIN V_RISK_GROUPFUNDS GFS ON CC.I_FUND = GFS.I_FUND INNER JOIN V_RISK_GROUPFUNDS GFS2 ON  GFS2.I_GROUP = GFS.I_GROUP AND  GFS2.I_SUBACCOUNT_TYPE = GFS.I_SUBACCOUNT_TYPE AND GFS2.I_SUBACCOUNT = GFS.I_SUBACCOUNT', 'SELECT 1 FROM V_RISK_ACCOUNT CC
INNER JOIN V_RISK_GROUPFUNDS GFS ON CC.I_FUND = GFS.I_FUND
INNER JOIN V_RISK_GROUPFUNDS GFS2 ON  GFS2.I_GROUP = GFS.I_GROUP  AND GFS2.I_SUBACCOUNT_TYPE = GFS.I_SUBACCOUNT_TYPE AND GFS2.I_SUBACCOUNT = GFS.I_SUBACCOUNT ', 'DEBAR_GROUP_VALUE;CC.I_FUND NOT IN (  SELECT A.I_FUND FROM V_RISK_GROUPFUNDS A WHERE A.I_GROUP IN (:DEBAR_GROUP_VALUE))|DEBAR_VALUE;CC.I_FUND NOT IN (:DEBAR_VALUE)|CONTROL_VALUE;GFS.I_GROUP IN (:CONTROL_VALUE)');

insert into RISK_FUND_BOUND_CFG (I_BOUND_ID, VC_BOUND_NAME, VC_LOAD_VALUE_SQL, VC_CALCU_SQL, VC_NEED_CALCU_SQL, VC_PROPERTY_KEY_VALUE)
values (0, '基金', 'CC.I_FUND = :I_FUND', ' ', 'SELECT 1 FROM V_RISK_ACCOUNT CC ', 'DEBAR_GROUP_VALUE;CC.I_FUND NOT IN (  SELECT A.I_FUND FROM V_RISK_GROUPFUNDS A WHERE A.I_GROUP IN (:DEBAR_GROUP_VALUE))|DEBAR_VALUE;CC.I_FUND NOT IN (:DEBAR_VALUE)|CONTROL_VALUE;CC.I_FUND IN (:CONTROL_VALUE)');
COMMIT;
END;